config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :bugs
  end

  root 'dashboards#home'
  post '/projects/:project_id/bugs/:id', to: 'bugs#bug_assignment', as: :assign
  post '/projects/:project_id/bugs/:id/status', to: 'bugs#status', as: :status

  devise_for :users, :controllers => {
    registrations: 'users/registrations'
  }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assisgnment.rb
class Assisgnment < ApplicationRecord
  self.table_name = "projects_users"
  belongs_to :project
  belongs_to :user
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :project
  belongs_to :reported_by, class_name: :User
  belongs_to :assigned_to, class_name: :User, optional: true
  has_one_attached :image

  validates :title, :status, :bugtype, presence: true
  validates :title, uniqueness: true
  validate :correct_image_type


  def correct_image_type
    if image.attached? && !image.content_type.in?(%w[image/png image/gif])
      errors.add(:image, 'Must be a PNG or GIF')
    end
  end
end


# askdnfjbaskjdflsadf

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :creator, class_name: :User

  has_many :bugs, dependent: :destroy
  has_many :assisgnments , dependent: :delete_all
  has_many :assigned_user, through: :assisgnments, source: :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :projects, foreign_key: :creator_id, dependent: :destroy
  has_many :bugs , through: :projects

  has_many :assisgnments
  has_many :project_assigned , through: :assisgnments ,source: :project

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :bug_project

  def index
    @bugs = @project.bugs
  end

  def show
    @bug = @project.bugs.find(params[:id])
  end

  def new
    @bug = @project.bugs.new
    authorize @bug
  end

  def create
    @bug = @project.bugs.new(bug_params)
    @bug.reported_by = current_user

    if @bug.save
      redirect_to [@project, @bug], notice: 'Bug successfully Reported.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @bug = @project.bugs.find(params[:id])
    authorize @bug
  end

  def update
    @bug = @project.bugs.find(params[:id])
    if @bug.update(bug_params)
      redirect_to [@project, @bug]
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bug = @project.bugs.find(params[:id])
    @bug.destroy
    redirect_to [@project, Bug] , notice: 'Bug successfully destroyed.'
  end

  def bug_assignment
    if @project
      @bug = @project.bugs.find(params[:id])
      if @bug
        if !(@bug.assigned_to_id)
          @bug.assigned_to = current_user
          @bug.save
        end
      end
    end
    redirect_to [@project, @bug]
  end

  def status
    @bug = @project.bugs.find(params[:id])
    if @project && @bug
      @bug.status = params[:status]
      @bug.save
    end
    redirect_to  [@project, @bug]
  end

  private

  def bug_project
    @project = Project.find(params[:project_id])
  end

  def bug_params
    params.require(:bug).permit(:title, :description, :deadline, :bugtype, :status, :image )
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    if current_user.usertype == 'Developer'
      @projects = current_user.project_assigned
    elsif current_user.usertype == 'QA'
      @projects = Project.all
    else
      @projects = current_user.projects.all
    end
  end

  def show
    @project = Project.find(params[:id])
    authorize @project
  end

  def new
    @project = current_user.projects.new
    authorize @project
  end

  def edit
    @project = Project.find(params[:id])
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.creator = current_user
    if params[:project][:object_id].any?
      params[:project][:object_id].reject!(&:empty?)
      @project.assigned_user = User.find( params[:project][:object_id])
    end
    authorize @project
    if @project.save
      redirect_to @project, notice: 'Project is successfully Created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @project = Project.find(params[:id])
    if params[:project][:object_id].any?
      params[:project][:object_id].reject!(&:empty?)
      @project.assigned_user = User.find( params[:project][:object_id])
    end
    authorize @project
    if @project.update(project_params)
      redirect_to @project, notice: 'Project is successfully Updated.'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_url, notice: 'Project is successfully Destroyed.'
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  private

    def sign_up_params
      params.require(:user).permit(:name, :email, :password, :usertype)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/bugs/_form.html.erb
<h2>Bug</h2>

<%= form_with(model: [@project, @bug], local: true) do |form| %>


  <% if @bug.errors.any? %>
    <ul>
    <% @bug.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="field form-group ">
    <%= form.text_field :title, placeholder: 'Bug/Feature Title' %>
  </div>


  <div class="field form-group ">
    <%= form.label :bugtype %><br>
    <%= form.select :bugtype, ['Bug', 'Feature'], selected: 'Bug' %>
  </div>


  <div class="field form-group ">
    <%= form.label :status %><br>
    <%= form.select :status, ['New', 'Started' , 'Resolved'], selected: 'new' %>
  </div>

  <div class="field form-group " >
    <%= form.label :deadline %><br>
    <%= form.date_select :deadline %>
  </div>

  <div class="field form-group " >
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div class="field form-group " >
    <%= form.label :image %><br>
    <%= form.file_field :image  %>
    <br>
    <br>
  </div>

  <div class="actions">
    <%= form.submit "Enter", class: "btn btn-secondary" %>
  </div>

<% end %>

<br/>

<button>
<%= link_to 'Back', project_bugs_path %>
</button>

app/views/bugs/edit.html.erb
<%= render 'form', bug: @bug, user: User.all %>

app/views/bugs/index.html.erb
<div class = "container ">
<h1> Project: <%= @project.title %> </h1>

<% @bugs.each do |bug| %>
  <div class="card border-secondary">
    <div class="card-header">
      <%= link_to bug.title, project_bug_path(@project, bug) %>

      <% if policy(bug).delete? %>
          <button >
          <%= link_to [@project, bug], method: :delete, data: {confirm: "Are you sure you want to delete this Bug?"} do %>
            Delete
          <% end %>
          </button>
      <% end %>

      <% if policy(bug).edit? %>
          <button >
          <%= link_to edit_project_bug_path(@project, bug) do %>
            Edit
          <% end %>
          </button>
      <% end %>

    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"> <p class="card-text"><%= bug.description %></p></li>
      <li class="list-group-item">
        <b>Started : </b>
        <%= bug.created_at.to_formatted_s(:long) %>
      </li>
      <li class="list-group-item">
        <% if bug.assigned_to_id? %>
          <i> Assgined</i>
        <% else %>
          <i> Not Assgined</i>
        <% end %>
      </li>
      <li class="list-group-item">
        <i> <%= bug.status %> </i>
      </li>
      <li class="list-group-item">deadline: <%= bug.deadline%></li>
    </ul>
  </div>
  <br/>
<% end %>

<h3> Summary </h3>

<ul >
  <li class="list-group-item"> Bugs:
    <%= @project.bugs.count %>
  </li>

  <li class="list-group-item"> Developers:
    <%= @project.assigned_user.count %>
  </i>
    <ol>
      <% @project.assigned_user.each do |user| %>
        <li><%= user.name %></li>
      <% end %>
    </ol>
</ul>

<button>
<%= link_to 'Back', projects_path %>
</button>
</div>

app/views/bugs/new.html.erb
<%= render 'form', bug: @bug, user: User.all %>

app/views/bugs/show.html.erb
<br/>
<div class="card" style="width: 18rem;">
  <div  class= " center card-img-top " >
    <% if @bug.image.attached? %>
      <%= image_tag(@bug.image) %>
      <br>
    <% end %>
  <div>
  <div class="card-body">
    <h5 class="card-title">
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><h2><%= @bug.title %></h2> </li>

        <% if policy(@bug).delete? %>
          <li class="list-group-item">
          <%= link_to [@project, @bug], method: :delete, data: {confirm: "Are you sure you want to delete this user?"} do %>
          Delete
          <% end %>
          </li>
        <% end %>
        <% if policy(@bug).edit? %>
          <li class="list-group-item">
          <%= link_to edit_project_bug_path(@project, @bug) do %>
          Edit
          <% end %>
          </li>
        <% end %>
        <li class="list-group-item">
        <h4>Reported by: <%= @bug.reported_by.name %></h4>
        </li>
      </ul>
    </h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <p class="card-text"><%= @bug.description %></p>
    </li>
    <li class="list-group-item">
      <% if @bug.bugtype == "Bug" %>
        <i>Bug</i>
      <% elsif @bug.bugtype == "Feature" %>
        <i>Feature</i>
      <%end%>
    </li>
    <li class="list-group-item">
      <% if @bug.assigned_to_id? %>
        <%= @bug.assigned_to.name %>
      <% else %>
        Not Taken
      <% end %>
    </li>
    <li class="list-group-item">
      <i > <%= @bug.deadline %></i>
    </li>
    <li class="list-group-item">
      <i> <%= @bug.status %> </i>
    </li>
    <% if (!@bug.assigned_to_id? && current_user.usertype == "Developer") %>
      <li class="list-group-item">
        <%= form_for assign_path(@bug.project, @bug) do |form| %>
          <%= form.submit "Assign the bug to Yourself"%>
        <% end %>
      </li>
    <% end %>
    <% if @bug.assigned_to == current_user %>
      <li class="list-group-item">
        <%= form_with url: status_path(@bug.project, @bug) do |form| %>
          <% if @bug.bugtype == "Bug" %>
            <%= form.select :status, ['New', 'Started','Resolved']%>
          <% else %>
            <%= form.select :status, ['New', 'Started','Completed']%>
          <% end %>
          <%= form.submit "Change Status"%>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<br/>
<button>
<%= link_to 'Back', project_bugs_path %>
</button>

app/views/dashboards/_developer.html.erb
<h1> Developers Window  </h1>

<a class = "btn btn-secondary" href="<%= projects_path %>">All Projects</a>

app/views/dashboards/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">BugZilla</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link" href="/users/sign_in">Sign in <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/users/sign_up">Sign Up</a>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
      </li>

      <% if current_user %>
        <li class="nav-item  btn btn-info" >
          <%= current_user.name %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
<%= render 'layouts/alerts'%>

app/views/dashboards/_manager.html.erb
<h1>Managers Window  </h1>
<a class = "btn btn-secondary" href="<%= projects_path %>">All Projects</a>
<br/>
<br/>
<% if policy(Project).new? %>
    <a class = "btn btn-secondary" href="<%= new_project_path %>">create new Project</a>
<% end %>

app/views/dashboards/_qa.html.erb
<h1> QAs Window  </h1>

<a  class = "btn btn-secondary" href="<%= projects_path %>">All Projects</a>

app/views/dashboards/home.html.erb
<% if current_user && current_user.usertype == 'Developer' %>
<%= render 'dashboards/developer' , projects: @projects %>

<% elsif current_user && current_user.usertype == 'Manager'%>
<%= render 'dashboards/manager' , projects: @projects %>

<% elsif current_user && current_user.usertype == 'QA' %>
<%= render 'dashboards/qa' , projects: @projects%>

<% else %>

<%= link_to 'Sign Up', new_user_registration_path %>
<%= link_to 'Sign in', new_user_session_path %>
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>

<% end %>

app/views/layouts/_alerts.html.erb
<% if notice %>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page"><p class="notice"><%= notice %></p></li>
  </ol>
</nav>
<% end %>

<% if alert%>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page"><p class="notice"><p class="alert"><%= alert %></p></li>
  </ol>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugzilla</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application'%>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'dashboards/header'%>
    <div style = " margin-left: 1rem ">
    <%= yield %>
    </div>

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with model: project, local: true do |form| %>
  <div class="field form-group ">
    <label for="title">Project Title</label>
    <%= form.text_field :title, class: 'form-control', placeholder: 'Project Title' %>
  </div>

  <div class="field form-group ">
    <label for="description">Project Description</label>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="field form-group ">
    <label for="users"><b>Select Developers</b></label>
    <br/>
    <%= form.collection_check_boxes(:object_id, user.where(:usertype => 'Developer'), :id, :name, {selected: @project.assigned_user.ids}, {multiple: true} ) %>
    <br/>
    <label for="users"><b>Select QA</b></label>
    <br/>
    <%= form.collection_check_boxes(:object_id, user.where(:usertype => 'QA'), :id, :name, {selected: @project.assigned_user.ids}, {multiple: true} ) %>
  </div>

  <div class="actions">
    <%= form.submit "Enter", class: "btn btn-secondary" %>
  </div>

<% end %>
<br/>

<button>
<%= link_to 'Back', projects_path %>
</button>

app/views/projects/edit.html.erb
<%= render 'form', project: @project, user: User.all %>

app/views/projects/index.html.erb
<div class = "container">
<h1>Projects</h1>

<% @projects.each do |project| %>
    <div class = "card border-secondary">
      <div class="card-header">
        <%= link_to project.title, project_path(project) %>
        <% if policy(project).delete? %>
          <button >
          <%= link_to project, method: :delete, data: {confirm: "Are you sure you want to delete this Project?"} do %>
          Delete
          <% end %>
          </button>
       <% end %>

        <% if policy(project).edit? %>
          <button >
          <%= link_to edit_project_path(project) do %>
            Edit
          <% end %>
          </button>
        <% end %>
      </div>

      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <p class="card-text"><%= project.description %></p>
        </li>
        <li class="list-group-item">
          <i class="far fa-clock pr-1"></i><b>Started : </b><%= project.created_at.to_date %>
        </li>
        <li class="list-group-item">
          <div class="white-text"><i class="fa fa-bug pr-1"></i> <b>Bugs: </b> <%= project.bugs.count %></div>
        </li>
        <li class="list-group-item">
          <div class="white-text"><i class="fa fa-user pr-1"> <b>Assigned Users: </b>  <%= project.assigned_user.count %> </i></div>
        </li>
      </ul>
  </div>
  <br/>
<% end %>

<br/>
<% if policy(Project).new? %>
  <a class = "btn btn-secondary" href="<%= new_project_path %>">Create new Project</a>
<% end %>
<br/>
<br/>

<button>
<%= link_to 'Back', root_path %>
</button>

</div>

app/views/projects/new.html.erb
<div class="container-fluid pt-5 mt-3">
  <%= render 'form', project: @project, user: User.all %>
</div>

app/views/projects/show.html.erb
<div class="card">
  <div class="card-header">
    <h2 ><%= @project.title %></h2>
  </div>
   <div class="card-header">
    <h2 class="h5">Project Manager: <%= @project.creator.name %></h2>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= @project.description %></li>
    <li class="list-group-item"><%= @project.created_at.to_date %></li>
    <li class="list-group-item"><i> Bugs: <%= @project.bugs.count %></i></li>
    <li class="list-group-item"><i> Users: <%= @project.assigned_user.count %></li>

    <li class="list-group-item">
      <ol class="mt-2">
        <% @project.assigned_user.each do |user| %>
          <li class="grey-text"><%= user.name %></li>
        <% end %>
      </ol>
    </li>
  </ul>
</div>

<br/>

<% if policy(@project).delete? %>
  <button>
  <%= link_to @project, method: :delete, data: {confirm: "Are you sure you want to delete this Project?"} do %>
    Delete
  <% end %>
  </button>
<% end %>

<% if policy(@project).edit? %>
  <button>
  <%= link_to edit_project_path(@project) do %>
    Edit
  <% end %>
  </button>
<% end %>

<br/>
<% if @project.bugs.count > 0 %>
  <br/>
  <%= link_to 'See Project Bugs', project_bugs_path(@project.id), class: 'white-text btn btn-secondary' %>
  <br/>
<% end %>

<br/>
<% if current_user.usertype == "QA" %>
  <a class = "btn btn-secondary"  href="<%= new_project_bug_path @project %>">create new Bug</a> </li>
<% end %>
<br/>
<br/>

<button>
<%= link_to 'Back', root_path %>
</button>